### ISSUE TITLE
JE-46991 Describe email: false in CS docs

### ISSUE THREAD

**Issue by vlobzakov** [vlobzakov/docs#21]
Describe email: false in CS docs: https://jelastic.team/browse/JE-46991 
Нужно пояснение по примеру изложенному в тикете.

В тикете написано:
с отправкой email:
return:
type: success
message: your message
**email: your email message** 

Делаю пример: 
```
type: install
name: "TEST: JE-22408 Add-on without environment"
description: |
  Describe email: false in CS docs
startPage: https://jelastic.com/
onInstall:
  - log: test
  - return:
      type: success
      message: Compute node unique identifier
      email: nonfalse
```
на почту приходит **Compute node unique identifier**

если пример сделать так:
```
type: install
name: "TEST: JE-22408 Add-on without environment"
description: |
  Describe email: false in CS docs
startPage: https://jelastic.com/
onInstall:
   - log: test
success:
    email: nonfalse
```

то на почту приходит сообщение: **nonfalse**
в обеих случаях если написать **email: false** то почта не приходит.
